import { StyleSheet } from 'react-native';

export const textStyles = StyleSheet.create({
  title: {
    color: 'white',
    fontFamily: 'ws-regular',
    fontSize: 64,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  h2: {
    color: 'white',
    fontFamily: 'ws-regular',
    fontSize: 40,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  h3: {
    color: 'white',
    fontFamily: 'ws-regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  subtitle: {
    color: 'white',
    fontFamily: 'ws-regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '500',
  },
  body: {
    color: 'white',
    fontFamily: 'ws-regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
  },
  bold: {
    color: 'white',
    fontFamily: 'ws-regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  small: {
    color: '#CAD1DB',
    fontFamily: 'ws-regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
  },
  pretitle: {
    color: '#CAD1DB',
    fontFamily: 'ws-regular',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'ws-bold',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.64,
    wordWrap: 'break-word',
  },
  link: {
    color: 'var(--Iris, #4B4DED)',
    fontFamily: 'ws-regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
  },
});
