name: Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy_ios:
    name: Deploy for ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform: [
          {runner: 'macos-latest', os: 'ios'},
          {runner: 'ubuntu-latest', os: 'android'}
        ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install deps
        run: npm install --force

      - name: Install dev-client
        run: npm install --force expo-dev-client

      - name: Create preview
        run: eas update --auto
