name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy_ios:
    name: Deploy ios and Android
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install deps
        run: npm install --force

      - name: Install dev-client
        run: npm install --force expo-dev-client

      - name: Create preview
        run: eas update --auto
